#!/bin/bash
set -e


echo "################################################################"
echo "####   Trouver mirroir + rapide FR et EU                     ###"
echo "################################################################"

sudo reflector -l 100 -f 50 -c BE -c NL -c FR -c DE -c GB --sort rate --threads 5 --verbose --save /tmp/mirrorlist.new && rankmirrors -n 0 /tmp/mirrorlist.new > /tmp/mirrorlist && sudo cp /tmp/mirrorlist /etc/pacman.d


echo "################################################################"
echo "####     Sauvegarde                                         ####"
echo "################################################################"


cat /etc/pacman.d/mirrorlist


